### ISSUE TITLE
Hide Typescript Errors from the User

### ISSUE THREAD

**Issue by calgagi** [The-Code-In-Sheep-s-Clothing/Spiel-Front#7]
I think it's due to trying to print out the error to the CLI

**Comment by montymxb** [comment]
Yeah, this is something that the backend should take care of. I imagine any unhandled error should be caught and wrapped up under a simple ```SpielError``` tag, so it at least doesn't crash TS.

**Comment by montymxb** [comment]
Restated as hiding typescript errors from the user, rather than just crashing on a 400 error code from the backend. There are a couple of situations where a typescript error pops up directly (such as when the server is unreachable) that should not show up to the user as raw errors. These need to be cleaned up a bit so that they are understandable to 6th/7th graders.
